apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: beers.beerdb.fosdem.org
spec:
  group: beerdb.fosdem.org
  scope: Namespaced
  names:
    plural: beers
    singular: beer
    kind: Beer
  versions:
  - name: v1
    storage: true
    served: true
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
